
import type { Lesson, Teacher, Question, NewsArticle, Grade, FileCategory, UploadedFile } from './types';

// This file contains the initial data for the application.
// This data is used as a fallback if the Firestore database is empty.

export const initialTeachers: Teacher[] = [
  { id: 'admin', name: 'Admin User', email: 'zakarya.belgaid@gmail.com', password: 'Zakarya14021996((', bio: 'The main administrator for Algo Tutor.', avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhZG1pbiUyMHdvbWFufGVufDB8fHx8MTc2MjkxNDcyNHww&ixlib=rb-4.1.0&q=80&w=1080', isApproved: true, role: 'admin' },
  { id: 'teacher-1', name: 'Jane Doe', email: 'jane@example.com', password: 'password', bio: 'Expert in C programming and data structures. Loves helping students understand complex topics.', avatarUrl: 'https://images.unsplash.com/photo-1592621385612-4d7129426394?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHx3b21hbiUyMHBvcnRyYWl0fGVufDB8fHx8MTc2Mjg4ODYyM3ww&ixlib=rb-4.1.0&q=80&w=1080', isApproved: true, role: 'teacher' },
  { id: 'teacher-2', name: 'John Smith', email: 'john@example.com', password: 'password', bio: 'Specializes in algorithm optimization and performance. 10+ years of industry experience.', avatarUrl: 'https://images.unsplash.com/photo-1624395213043-fa2e123b2656?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxtYW4lMjBwb3J0cmFpdHxlbnwwfHx8fDE3NjI4NTg1MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080', isApproved: true, role: 'teacher' },
  { id: 'teacher-3', name: 'Emily White', email: 'emily@example.com', password: 'password', bio: 'A passionate educator with a knack for making difficult concepts easy to grasp.', avatarUrl: 'https://images.unsplash.com/photo-1679611978819-f10168367155?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx3b21hbiUyMGZhY2V8ZW58MHx8fHwxNzYyOTQ2NzEzfDA&ixlib=rb-4.1.0&q=80&w=1080', isApproved: true, role: 'teacher' },
  { id: 'teacher-4', name: 'Michael Brown', email: 'michael@example.com', password: 'password', bio: 'Focuses on competitive programming and algorithmic problem-solving techniques.', avatarUrl: 'https://images.unsplash.com/photo-1619182597083-17bda72c1d56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxtYW4lMjBmYWNlfGVufDB8fHx8MTc2MjkxNDYwNnww&ixlib=rb-4.1.0&q=80&w=1080', isApproved: false, role: 'teacher' }
];

export const initialQuestions: Question[] = [
    { id: 'q1', teacherId: 'teacher-1', studentName: 'Alice', studentEmail: 'alice@example.com', questionText: 'How do pointers work in C?', answerText: 'A pointer is a variable that stores the memory address of another variable. This allows you to indirectly access and modify the data stored at that address.', status: 'answered', isPinned: true },
    { id: 'q2', teacherId: 'teacher-2', studentName: 'Bob', studentEmail: 'bob@example.com', questionText: 'What is the time complexity of quicksort?', answerText: 'The average time complexity of Quicksort is O(n log n), but its worst-case complexity is O(n^2).', status: 'answered', isPinned: true },
    { id: 'q3', teacherId: 'teacher-1', studentName: 'Charlie', studentEmail: 'charlie@example.com', questionText: 'Can you explain recursion?', status: 'pending', isPinned: false },
    { id: 'q4', teacherId: 'admin', studentName: 'Dave', studentEmail: 'dave@example.com', questionText: 'Where can I find the course syllabus?', status: 'pending', isPinned: false },
];

export const initialNews: NewsArticle[] = [
    { id: 'news-1', slug: 'welcome-to-algo-tutor', title: 'Welcome to the New Algo Tutor Platform!', summary: 'We are excited to launch our new interactive platform designed to help you master algorithms.', content: 'This platform offers a range of features including interactive lessons, a Q&A section with expert teachers, and a place to download all your course materials. We hope you find it a valuable resource in your learning journey.', author: 'Admin User', publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjb2RlfGVufDB8fHx8MTc2Mjg2MjU5NHww&ixlib=rb-4.1.0&q=80&w=1080' },
    { id: 'news-2', slug: 'midterm-exam-schedule', title: 'Midterm Exam Schedule Announced', summary: 'The schedule for the upcoming midterm exams has been posted. Please check the files section.', content: 'The schedule for the upcoming midterm exams is now available in the "Files" section of the platform. Please review it carefully and reach out to your instructor if you have any questions. Good luck with your preparation!', author: 'Jane Doe', publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxleGFtJTIwc2NoZWR1bGV8ZW58MHx8fHwxNzYyOTQ2MTc5fDA&ixlib=rb-4.1.0&q=80&w=1080' },
];

export const initialUploads: UploadedFile[] = [];


export const lessonCode: Pick<Lesson, 'id' | 'example' | 'exercise'>[] = [
  { id: 'c-basics-01', example: '#include <stdio.h>\n\nint main() {\n  printf("Hello, World!");\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  printf("Your Name");\n  return 0;\n}' } },
  { id: 'c-syntax-02', example: '#include <stdio.h>\n\nint main() {\n  // This is a comment\n  printf("Semicolons are important!");\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  printf("Algo is fun!");\n  return 0;\n}' } },
  { id: 'c-variables-03', example: '#include <stdio.h>\n\nint main() {\n  int myNum = 15;\n  printf("My favorite number is: %d", myNum);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int answer = 42;\n  printf("The answer is %d", answer);\n  return 0;\n}' } },
  { id: 'c-data-types-04', example: '#include <stdio.h>\n\nint main() {\n  int myNum = 5;\n  float myFloat = 5.99;\n  char myLetter = \'D\';\n  printf("%d\\n", myNum);\n  printf("%f\\n", myFloat);\n  printf("%c\\n", myLetter);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int items = 50;\n  float cost = 25.5;\n  char initial = \'A\';\n  printf("Items: %d\\n", items);\n  printf("Cost: %.2f\\n", cost);\n  printf("Initial: %c\\n", initial);\n  return 0;\n}' } },
  { id: 'c-operators-05', example: '#include <stdio.h>\n\nint main() {\n  int x = 10;\n  int y = 5;\n  int sum = x + y;\n  printf("Sum: %d", sum);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int a = 7;\n  int b = 8;\n  printf("Product: %d", a * b);\n  return 0;\n}' } },
  { id: 'c-control-flow-06', example: '#include <stdio.h>\n\nint main() {\n  int time = 20;\n  if (time < 18) {\n    printf("Good day.");\n  } else {\n    printf("Good evening.");\n  }\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int num = -5;\n  if (num > 0) {\n    printf("Positive");\n  } else {\n    printf("Negative or Zero");\n  }\n  return 0;\n}' } },
  { id: 'c-switch-07', example: '#include <stdio.h>\n\nint main() {\n  int day = 4;\n  switch (day) {\n    case 1:\n      printf("Monday");\n      break;\n    case 2:\n      printf("Tuesday");\n      break;\n    default:\n      printf("Another day");\n  }\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int month = 8;\n  switch (month) {\n    case 8:\n      printf("August");\n      break;\n    default:\n      printf("Other month");\n  }\n  return 0;\n}' } },
  { id: 'c-loops-08', example: '#include <stdio.h>\n\nint main() {\n  for (int i = 0; i < 5; i++) {\n    printf("%d\\n", i);\n  }\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint i = 1;\n  while (i <= 10) {\n    printf("%d\\n", i);\n    i++;\n  }\n  return 0;\n}' } },
  { id: 'c-arrays-09', example: '#include <stdio.h>\n\nint main() {\n  int myNumbers[] = {25, 50, 75, 100};\n  printf("%d", myNumbers[0]); // Outputs 25\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int marks[3];\n  marks[0] = 90;\n  marks[1] = 85;\n  marks[2] = 95;\n  printf("%d", marks[1]);\n  return 0;\n}' } },
  { id: 'c-pointers-10', example: '#include <stdio.h>\n\nint main() {\n  int myAge = 43;\n  int* ptr = &myAge;\n  printf("%p\\n", ptr); // address\n  printf("%d\\n", *ptr); // value\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  int num = 10;\n  int* pNum = &num;\n  *pNum = 20;\n  printf("%d", num);\n  return 0;\n}' } },
  { id: 'c-functions-11', example: '#include <stdio.h>\n\nvoid myFunction() {\n  printf("I just got executed!");\n}\n\nint main() {\n  myFunction();\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nvoid greet() {\n  printf("Hello there!");\n}\n\nint main() {\n  greet();\n  return 0;\n}' } },
  { id: 'c-structs-12', example: '#include <stdio.h>\n\nstruct Person {\n  char name[50];\n  int age;\n};\n\nint main() {\n  struct Person p1;\n  p1.age = 30;\n  printf("Age: %d", p1.age);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n#include <string.h>\n\nstruct Car {\n  char brand[50];\n  int year;\n};\n\nint main() {\n  struct Car c1;\n  strcpy(c1.brand, "Ford");\n  c1.year = 2022;\n  printf("Year: %d", c1.year);\n  return 0;\n}' } },
  { id: 'c-recursion-13', example: '#include <stdio.h>\n\nint sum(int k) {\n  if (k > 0) {\n    return k + sum(k - 1);\n  } else {\n    return 0;\n  }\n}\n\nint main() {\n  int result = sum(10);\n  printf("%d", result);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nlong long factorial(int n) {\n  if (n >= 1) {\n    return n * factorial(n - 1);\n  } else {\n    return 1;\n  }\n}\n\nint main() {\n  printf("Factorial of 5 is %lld", factorial(5));\n  return 0;\n}' } },
  { id: 'c-constants-14', example: '#include <stdio.h>\n\nint main() {\n  const int MINUTES_PER_HOUR = 60;\n  // MINUTES_PER_HOUR = 30; // this would cause an error\n  printf("%d", MINUTES_PER_HOUR);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  const float PI = 3.14;\n  printf("The value of PI is: %f", PI);\n  return 0;\n}' } },
  { id: 'c-booleans-15', example: '#include <stdio.h>\n#include <stdbool.h>\n\nint main() {\n  bool isProgrammingFun = true;\n  if (isProgrammingFun) {\n    printf("Programming is fun!");\n  }\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n#include <stdbool.h>\n\nint main() {\n  bool isLightOn = false;\n  printf("Is the light on? %d", isLightOn);\n  return 0;\n}' } },
  { id: 'c-break-continue-16', example: '#include <stdio.h>\n\nint main() {\n  for (int i = 0; i < 10; i++) {\n    if (i == 4) {\n      break; // Stop the loop\n    }\n    printf("%d\\n", i);\n  }\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  for (int i = 0; i < 10; i++) {\n    if (i == 5) {\n      continue; // Skip this iteration\n    }\n    printf("%d\\n", i);\n  }\n  return 0;\n}' } },
  { id: 'c-strings-17', example: '#include <stdio.h>\n\nint main() {\n  char greetings[] = "Hello World!";\n  printf("%s", greetings);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  char carName[] = "Volvo";\n  printf("%s", carName);\n  return 0;\n}' } },
  { id: 'c-function-parameters-18', example: '#include <stdio.h>\n\nvoid greet(char name[]) {\n  printf("Hello %s\\n", name);\n}\n\nint main() {\n  greet("John");\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nvoid printSum(int x, int y) {\n  printf("Sum is: %d", x + y);\n}\n\nint main() {\n  printSum(5, 3);\n  return 0;\n}' } },
  { id: 'c-user-input-19', example: '#include <stdio.h>\n\nint main() {\n  int myNum;\n  printf("Type a number and press enter: \\n");\n  scanf("%d", &myNum);\n  printf("Your number is: %d", myNum);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nint main() {\n  char firstName[30];\n  printf("Enter your first name: \\n");\n  scanf("%s", firstName);\n  printf("Hello %s.", firstName);\n  return 0;\n}' } },
  { id: 'c-enums-20', example: '#include <stdio.h>\n\nenum Level {\n  LOW,\n  MEDIUM,\n  HIGH\n};\n\nint main() {\n  enum Level myVar = MEDIUM;\n  printf("%d", myVar);\n  return 0;\n}', exercise: { question: '', solution: '#include <stdio.h>\n\nenum Status {\n  PENDING,\n  APPROVED,\n  REJECTED\n};\n\nint main() {\n  enum Status myStatus = APPROVED;\n  printf("Status code: %d", myStatus);\n  return 0;\n}' } }
];

export const grades: Grade[] = [
  { id: 'grade-1', name: 'First Year' },
  { id: 'grade-2', name: 'Second Year' },
];

export const fileCategories: FileCategory[] = [
  { id: 'cat-1', name: 'TD', description: 'Travaux Dirigés (Directed Work)' },
  { id: 'cat-2', name: 'TP', description: 'Travaux Pratiques (Practical Work)' },
  { id: 'cat-3', name: 'Cours', description: 'Lecture Notes and Slides' },
];

